# This is a basic workflow that is manually triggered

name: Build to tokens to org project

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [workflow_dispatch]

# Create a PR on https://github.com/adobocorp/pinoycoderz-tokens.git
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: npm run build --if-present
  # build-and-test:
  #   runs-on: ubuntu-latest
  #   name: Build and create a pull request
  #   steps:
  #     - uses: actions/setup-node@v3.8.1
  #     - name: build style dictionary
  #       run: npm run build
  #     - name: list build output
  #       run: ls build
