# This is a basic workflow that is manually triggered

name: Build to tokens to org project

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [workflow_dispatch]

# Create a PR on https://github.com/adobocorp/pinoycoderz-tokens.git
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and create a pull request
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - run: npm run build
      - run: echo build/scss/_variables.scss
