# This is a basic workflow that is manually triggered

name: Build to tokens to org project

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and create a pull request
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - run: npm run build
      - run: git config user.name "GitHub Actions Bot"
      - run: git config user.email "<>"
      - run: git checkout -b temp-build
      - run: git add .
      - run: gh pr create --title 'Merge build into base_branch' --body 'Created by Github action'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
